export const properties = [
    "NO CTM",
    "NO, DENTRATE PA DENTRO",
    "NO, YA TE PUSISTE LA VACUNA DE AMOR?",
    "NO, EL VIRUS AUN NO SE PONE BUENA PERSONA",
    "USTED ES WN O SE HACE?",
    "NO, AFUERA HAY TORMENTA DE CACA",
    "TANTO TE IMPORTA SALIR, TANTO TE IMPORTA PERRO QL ~ Rosa",
    "NO, EL CORONAVIRUS E MALO, E MALO, E MAOMENO, E MAOMENO 🎵"
];
